[package]
name = "blake2-avx2-sneves"
version = "0.0.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]
edition = "2018"

[dependencies]

[build-dependencies]
cc = "1.0.37"

[dev-dependencies]
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
hex = "0.3.2"
